name: Deploy Evidence Site

on:
  push:
    branches: [ main ]
  schedule: 
    - cron: '15 14 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install & Build
        run: |
          npm install
          npm run sources
          npm run build
      
      - name: Add NoJekyll
        # 即使在主页仓库，这一步也是“救命稻草”
        # 它强制 GitHub 开放以 _ 开头的文件夹（如 _app）
        run: touch build/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
